[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["@anthropic-ai/sdk"]
  node_bundler = "esbuild"

[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PRIVATE_TARGET = "server"
  NODE_VERSION = "18"

[[edge_functions]]
  path = "/api/*"
  function = "api"

[dev]
  framework = "next"